### PR TITLE
Make `available_markets` optional

### PR DESCRIPTION
**Pull request by hrkfdn**
## Description

Fixes https://github.com/ramsayleung/rspotify/issues/285

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Test suite was extended

### CODE REVIEW

**Comment by marioortizmanero** [comment]
Could you please add these changes to the changelog? You might have to make a new entry, I forgot about that. We can release it for 0.11.3.

**Comment by hrkfdn** [comment]
@marioortizmanero Like this?

**Comment by marioortizmanero** [comment]
Perfect, thanks a lot for the contribution! <3

**Review by marioortizmanero — APPROVED** [review]

**Comment by hrkfdn** [comment]
@marioortizmanero Sure :)! Do you have a rough estimate on when you'll release 0.11.3?

**Comment by marioortizmanero** [comment]
I'd like to close #281. I'm still not fully sure about how to approach for `rspotify-model`, but we need it ASAP because otherwise most of the links in the docs are broken. Also merging all the pending PRs and we can release a new version, but that should be pretty easy.

**Pull request merged**
