### PR TITLE
Implement `Into<&'static str>` for all enums

### PR DESCRIPTION
**Pull request by SabrinaJewson**
## Description

Derives both `AsRef<str>` and `Into<&'static str>` (via `From<{the enum}> for &'static str`) for all the enums.

Note: there’s a `#[derive]` in here that `rustfmt` explodes on to 13 lines. I don’t really like it but I also can’t separate the derives into two lines because rustfmt just merges them together again 😄

Also makes `Market` `Copy`, just so I can avoid code duplication between `AsRef<str>` and `From<Market> for &'static str`.

## Motivation and Context

This makes the enums useful in more places, since the lifetime of the string is not actually tied to the lifetime of the enum.

## Dependencies 

None.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

Please also list any relevant details for your test configuration

- [x] Test A: `cargo test -p rspotify-model`

### CODE REVIEW

**Comment by SabrinaJewson** [comment]
Note that this would allow lots of the endpoint functions to use `x.map(|x| x.into())` instead of `x.as_ref().map(|x| x.as_ref())` so that’s nice. And making `Market` `Copy` also opens up the door for changing all those `Option<&Market>` parameters to take `Option<Market>` instead; but I haven’t done that yet because the merge conflicts with #328 would be a pain.

**Comment by marioortizmanero** [comment]
Yeah, `IntoStaticStr` seems better overall. Is there a point in also having `AsRefStr` now?

**Comment by SabrinaJewson** [comment]
I suppose not. It might be useful occasionally — your call really.

**Comment by marioortizmanero** [comment]
I would personally remove it, but let's wait for @ramsayleung to have a third opinion.

**Comment by ramsayleung** [comment]
If we have `IntoStaticStr`, I think there is unnecessary to keep `AsRefStr`, as @SabrinaJewson points out:

> since the lifetime of the string is not actually tied to the lifetime of the enum.

**Comment by SabrinaJewson** [comment]
I’ve gone ahead and removed those implementations, also replacing `&Market` types with `Market` to prevent `(*x).into()`s everywhere (this is possible now since `Market: Copy`).

**Pull request merged**
