### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by ramsayleung**
Add issue templates to standardize the information that contributors to include when they open issues and pull requests.

### CODE REVIEW

**Comment by marioortizmanero** [comment]
Looks Good To Me! I also wanted to create a template like this.

**Comment by ramsayleung** [comment]
Yep, by the way, I have enabled required reviews for pull requests, by following the [official guide](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-reviews-for-pull-requests)

Now at lease one approving review is required before merging the pull request, and I guess you have the permission to approve this review. 

Just trying to make the development process as standard as possible :)

**Comment by marioortizmanero** [comment]
That's great! I agree with you. You can merge this if you want.

**Comment by ramsayleung** [comment]
I think it's better to walk through the standard process(the first try), and I am waitting for your approving review :)

**Comment by marioortizmanero** [comment]
Ha sure I forgot about that :P

**Review by marioortizmanero — APPROVED** [review]

**Pull request merged**
