### PR TITLE
Separate crates

### PR DESCRIPTION
**Pull request by marioortizmanero**
## Description

Some work towards #191. I've ended up separating the crates but leaving the auth, http and client ones mixed under `rspotify_client` until #173 is worked on.

## Motivation and Context

See #191

## Dependencies 

Should be the same

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

This change means that types like `FullAlbum` in the model now have to be public.

## How Has This Been Tested?

The previous tests still work now. Same goes for the examples (which by the way I had to fix because they weren't working)

---

Closes #191

### CODE REVIEW

**Comment by marioortizmanero** [comment]
I think the best organization for our crates will be the following:

* `src/`: the Spotify client, with the endpoints and everything needed to access the API
* `rspotify-model/`: with the model
* `rspotify-http/`: with the HTTP client abstraction features
* `rspotify-auth/`: with the Auth functionalities, exclusively

In this PR `rspotify-http`, `rspotify-auth` and `src` are inside `src` because they are too tied together. I was going to make the client a separate crate, like `rspotify-client` but figured it's not really worth it. I can understand that someone might want to use `rspotify-model ` or `rspotify-http` on their own, but using `rspotify-client` would be just like using `rspotify`, which is just confusing, in my opinion.

**Comment by marioortizmanero** [comment]
This is now ready for review. Please @ramsayleung take a look at #166 after merging this; it's been open for a while and I would like to finish it before #173 if possible.

**Comment by ramsayleung** [comment]
Since `rspotify-http`, `rspotify-auth` are too tied together, and we have to keep working on the separating crates after #173 is done, would you like to consider working on this PR after #173 and #166 merged, so we don't have to change it for twice, just to reduce some unnecessary context-switch work

> Please @ramsayleung take a look at #166 after merging this; it's been open for a while and I would like to finish it before #173 if possible.

Sorry for this, I don't realize that it's ready to review, I will check it on the weekend :)

**Comment by marioortizmanero** [comment]
> Since rspotify-http, rspotify-auth are too tied together, and we have to keep working on the separating crates after #173 is done, would you like to consider working on this PR after #173 and #166 merged, so we don't have to change it for twice, just to reduce some unnecessary context-switch work

The thing is that this is already discussed and implemented, so it's preferable to do it in two steps in my opinion. It doesn't really matter that it's done all at once.

> Sorry for this, I don't realize that it's ready to review, I will check it on the weekend :)

Great, thanks!

**Comment by marioortizmanero** [comment]
If you'd rather not merge this, I can just start #173 on a new PR based on this branch instead of master, by the way.

**Comment by ramsayleung** [comment]
> The thing is that this is already discussed and implemented, so it's preferable to do it in two steps in my opinion. It doesn't really matter that it's done all at once. This way that the #173 PR will be split up and probably easier to review, and I have more clear how the structure is supposed to go, too.

It will be easier to review if you split it into two PR, and polishing it step by step is also a good idea. I would merge this after I review it. But before that, we need to keep our eyes on #166 :-)

**Comment by marioortizmanero** [comment]
This will be marked as a draft until I implement #173, and I'll build said PR over this branch. That way the work will be split up into various PRs instead of a huge one.

**Comment by ramsayleung** [comment]
I think the separated crates would look like this:

rspotify-arch

**Review by ramsayleung — APPROVED** [review]

**Comment by ramsayleung** [comment]
I am not sure if this PR ready to merge, even though I have merged all separated PRs

**Comment by marioortizmanero** [comment]
Yes, you can merge it.

**Comment by ramsayleung** [comment]
Finally, it takes so long, but we reached it :)

**Comment by marioortizmanero** [comment]
Yes I can't believe it! We're getting closer to v0.11 :)

**Pull request merged**
