### PR TITLE
Implement async/await on all methods

### PR DESCRIPTION
**Pull request by Rigellute**
This is going to be a large pull request (we could merge this into a side branch?).

TODO
- [x] Implement async/await on all methods
- [x] Update examples
- [x] Fix tests

### CODE REVIEW

**Comment by ramsayleung** [comment]
ooh,  it seems we are doing the same job to add support for async/await(something is conflicting, but something is not). Would you like merge your branch into my WIP [branch: support-for-async-await](https://github.com/ramsayleung/rspotify/tree/ramsay/support-for-async-await). By the way, I think it will be better you will need to check these two issues first:
https://github.com/ramsayleung/rspotify/issues/79
https://github.com/ramsayleung/rspotify/issues/78

**Comment by Rigellute** [comment]
Hehe whoops! I should have checked the issues before I started (only checked pull requests).

I actually learnt a lot about async/await in Rust by doing this so still happy to have done it.

I've got my branch to the point where `cargo check` passes, the tests also all compile now (including all examples) but the async tests are a little flaky (guessing there is a timeout or something). Different tests fail on each run.

And sure, if my work is mergable we can merge into your branch!

**Comment by Rigellute** [comment]
The most interesting part (for me at least) was updating the `internal_call` method to leverage generic json parsing from the response - this let's us not need to the `convert_result` method.
https://github.com/ramsayleung/rspotify/pull/80/files#diff-36ae331d0439539ddec0f366a67f90cbR136

**Comment by Rigellute** [comment]
Also, I nearly got carpal tunnel during this refactor 😄 .

Luckily vim macros came to the rescue.

Only running tests are failing now, which is great!

Any ideas on how to fix this?

```
dispatch dropped without returning error
```

This looks like a timeout

**Comment by ramsayleung** [comment]
> The most interesting part (for me at least) was updating the internal_call method to leverage generic json parsing from the response

Wow, thanks for your head-up,  it's amazing to take advantage of generic from the reqwest response. 

> I actually learnt a lot about async/await in Rust by doing this so.

So do I

> And sure, if my work is mergable we can merge into your branch!

Definitely Yes, you could merge into my branch, you have done a huge work for me. Would you like to resend a PR to my branch: `support-for-async-await`? Because I am not only updating the old endpoint functions to `async/await`, but also keep the old blocking endpoint functions with a new additional feature `blocking`, then other developers could choose API by their flavor.

**Comment by ramsayleung** [comment]
> Luckily vim macros came to the rescue.

Perhaps Emacs could save you either(just a joke).

> Any ideas on how to fix this? dispatch dropped without returning error

which test is failed?

**Comment by Rigellute** [comment]
Awesome @ramsayleung! Will send this PR to your branch! 
Just noticed that the code in the docs is also failing, will fix now (this is such an amazing feature of Rust)

**Comment by ramsayleung** [comment]
Notes that I think the next release of `Rspotify` will be a huge break change because of the support for `async/await`, which definitely breaks backward compatibility. So I decide to make an other break change into the next release, just to shorten the import path:
before:
```
use rspotify::spotify::client::Spotify;
use rspotify::spotify::oauth2::SpotifyClientCredentials;
```
 
after:
```
use rspotify::client::Spotify;
use rspotify::oauth2::SpotifyClientCredentials;
```

the `spotify` mod is unnecessary, so I just remove it. Maybe it will confuse you when you make a new PR to merge into my branch.

**Comment by Rigellute** [comment]
All the tests are passing! Looks like async/await is good to go!

Thanks for the heads up regarding the import paths.

Your plan to keep the blocking endpoints as a feature is a great idea.

**Comment by ramsayleung** [comment]
Why do you change the base branch back to `master` branch?

**Comment by Rigellute** [comment]
I am leaving this branch as is for now for my own reference and to preserve things in case of a bad merge/rebase. 

I forked this branch and applying it to your branch.

**Comment by Rigellute** [comment]
Closing this in favour of #81

**Pull request closed without merging**
