### PR TITLE
Fix: Typo of explicit restriction in `RestrictionReason`

### PR DESCRIPTION
**Pull request by hrkfdn**
## Description

Looks like there is a typo in the enum values. Not sure if this would considered a breaking change since the enum options are changing.

## Motivation and Context

https://github.com/hrkfdn/ncspot/issues/844

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?

See link above. I didn't explicitly test it, but it's surely a typo :)

### CODE REVIEW

**Comment by hrkfdn** [comment]
Thanks @marioortizmanero, just out of curiosity: is a release planned anytime soon?

**Comment by marioortizmanero** [comment]
I was hoping to merge #331, #329, #327 and #305 as a new 0.12 release, if that's fine with you. They should be done already and only need feedback before merging.

**Comment by marioortizmanero** [comment]
Another option is to merge all of the PRs except for #305, which is the truly breaking & bigger change, and release a 0.11.6 release in the meanwhile. But it depends on how fast we can merge the other ones and etc.

**Comment by hrkfdn** [comment]
Sooo @marioortizmanero, any plans for a bugfix release? :sweat_smile:

**Comment by hrkfdn** [comment]
Thanks @ramsayleung ❤️

**Pull request merged**
