### PR TITLE
get_token processing can be done in two parts

### PR DESCRIPTION
**Pull request by braincow**
This patch separates get_token functionality into two different functions while still maintaining legacy compatibility where user is queried on the command line for return URL address.

Separating the behavior allows handling request and verification of received token in code. For example: I am working on a small app that spawns a simple http server to localhost to wait for users browser to return back from Spotify website. Thus user never needs to enter the values themselves to console.

### CODE REVIEW

**Comment by braincow** [comment]
This is the app where I am testing the feasibility of this type of approach: https://github.com/braincow/scotty

**Comment by ramsayleung** [comment]
Great, it looks clearer after refactoring `get_token` into two functions. And it seems there is a conflict between master and your branch, could resolve it first ?

**Comment by braincow** [comment]
@ramsayleung Conflict resolved now. (...and it appears that I caused it with my previous logging related pull request. "My bad" :D)

**Comment by ramsayleung** [comment]
It's great, merged ~~

**Pull request merged**
