### PR TITLE
upgrade rspotify to 0.11.5

### PR DESCRIPTION
**Pull request by ramsayleung**
## Description

Upgrade rspotify to v.0.11.5

## Motivation and Context

Fix https://github.com/ramsayleung/rspotify/issues/307

## Dependencies 

None

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## How has this been tested?

All CI checks should pass.

## Is this change properly documented?

Yes

### CODE REVIEW

**Review by marioortizmanero — CHANGES_REQUESTED** [review]
You forgot to bump the other crates' version numbers

**Comment by ramsayleung** [comment]
Oooh, my bad, I forgot to upgrade the version number of `rspotify-http`

**Review by marioortizmanero — APPROVED** [review]

**Comment by wael444** [comment]
crates.io still reports 0.11.4, is it slow?

**Comment by ramsayleung** [comment]
This PR just upgraded the version number in `cargo.toml` to `v0.11.5`, we need to publish the new version to crates.io. Then we have a Github Action job to handle this workflow, which is triggered by creating a new git tag.

**Pull request merged**
