### PR TITLE
Extern crate, Cargo.toml cleanup

### PR DESCRIPTION
**Pull request by marioortizmanero**
`extern crate` is no longer needed after Rust 2018, so I've removed all of them, using `use` in its place.

I also removed some unnecessary crates:
* `base64`: not used at all
* `env_logger`: not used at all
* `url`: not used at all
* `itertools`: only used once in `client.rs`, found a cleaner solution to avoid using `iproduct`

And other small improvements in `Cargo.toml`.

The one thing I don't know how to solve is the `reqwest`-related features. Wouldn't it make sense to just remove these `extern crate`? The `Cargo.toml` will already make sure the correct features for `reqwest` are being used.

### CODE REVIEW

**Comment by ramsayleung** [comment]
Thanks for your cleanup, it does remove some unnessary dependencies, which will leads to a smaller binary/crate.

> Wouldn't it make sense to just remove these extern crate?

Yes, it makes sense to let `Cargo.toml` to manage the features and crates. If you want to know more about `reqwest`-related features, you could this PR https://github.com/ramsayleung/rspotify/pull/76, which tried to cross compile when using this crate. Perhaps you could try to remove these `extern crate reqwest` like other crates, and check whether it will fail in the CI of cross-compilation or not. I could merge this PR after you try.

**Comment by marioortizmanero** [comment]
Managed to get it working! Check out the changes in `Cargo.toml`. Only the occasional tests fail now.

**Comment by ramsayleung** [comment]
You have modified tons of files, making it painful for me to review all modification, merged finally :)

**Comment by marioortizmanero** [comment]
Thanks a lot! Most of the files modified were done automatically to remove the `extern crate`.

**Pull request merged**
