### PR TITLE
Add async/await

### PR DESCRIPTION
**Pull request by Rigellute**
Purpose of this PR is to track the progress of migrating rspotify to using async/await

### CODE REVIEW

**Comment by ramsayleung** [comment]
I have to say it's a large pull request, and it seems I have created too many examples which makes it some kind of tedious to refactor.

**Comment by Rigellute** [comment]
Hehe it's acutally awesome that you've documented it all so well, made building `spotify-tui` much easier.

If you like, you could create a pre-release based on this branch and I can test it out over in `spotify-tui`?

**Comment by ramsayleung** [comment]
> If you like, you could create a pre-release based on this branch and I can test it out over in spotify-tui?

I have create an alpha release: https://github.com/ramsayleung/rspotify/releases/tag/v0.9-alpha
Or do you mean create a pre-release of Rust crate?

**Comment by Rigellute** [comment]
I've refactored `spotify-tui` to use async/await (in the end I pointed my `Cargo.toml` to this repo instead of using crates.io).

One major issue I see is that some requests don't have responses and so my update to `internal_call` fails due to that method always invoking `.json()`.

I now see why you had a separate `convert_result` (whoops!). I will correct this.

**Comment by Rigellute** [comment]
Corrected here #84

**Comment by ramsayleung** [comment]
By the way, is performance improved after switching to `async/await`?

**Comment by Rigellute** [comment]
@ramsayleung doesn't look like performance improved much (lol) - but this is quirk of the architecture of `spotify-tui`.

Adding async/await is still a move in the right direction though!

**Comment by ramsayleung** [comment]
Update `README.md`, `CHANGELOG.md`, bump package version to v0.9, get ready to merge into master :)

**Comment by Rigellute** [comment]
Nice one @ramsayleung!

**Pull request merged**
